### ISSUE TITLE
Serializer Extend

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client#11]
Hi,
Sorry for the question. But I have this metadata yml

**Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType:
    properties:
        hotel:
            expose: true
            access_type: public_method
            serialized_name: Hotel
            accessor:
                getter: getHotel
                setter: setHotel
            type: Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\HotelAType
        mealPlans:
            expose: true
            access_type: public_method
            serialized_name: MealPlans
            accessor:
                getter: getMealPlans
                setter: setMealPlans
            type: array<Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\MealPlansAType\MealPlanAType>
            xml_list:
                inline: false
                entry_name: MealPlan
                skip_when_empty: true**

This class have this properties: 

class HotelMealPlansNotifRSType extends BaseController
{

    /**
     * @property \Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\HotelAType
     * $hotel
     */
    private $hotel = null;

    /**
     * @property
     * \Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\MealPlansAType\MealPlanAType[]
     * $mealPlans
     */
    private $mealPlans = null;
}
   

So far, everything is correct.  But this class extends from another: BaseController. I need to exclude the parent's class properties in  **JMS\Serializer\Metadata\PropertyMetadata Object**

With exclude : true, works from the HotelMealPlansNotifRSType but not from the extended properties.

**Comment by goetas** [comment]
is the `BaseController`  class generated by the soap client?

**Comment by victorgp89** [comment]
No, I implemented it because I need a dependency injector and another properties to create and answer.

**Comment by goetas** [comment]
> No, I implemented it because I need a dependency injector and another properties to create and answer.

not suggested approach... 

to exclude the properties in `BaseController` you have to define manually a YAML metadata file for the `BaseController` and exclude its properties.

Metadata definitions are per-class.

**Comment by victorgp89** [comment]
So if I need to serializer a native Controller phalcon class it's that
simple as:

Phalcon\Mvc\Controller:
     exclude: true


2017-06-01 16:55 GMT+02:00 Asmir Mustafic <notifications@github.com>:

**Comment by goetas** [comment]
it is, you have to:

```yml
Phalcon\Mvc\Controlle:
    exclusion_policy: NONE
```

**Comment by victorgp89** [comment]
Still not working. I have created a yml file for the Phalcon \ Mvc \
Controller and for Phalcon \ DI \ Injectable. And add the metadir to
serializer:

//add Soap BaseController info
$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Core',
'Igm\Synergy\Application\Core');


In metadata/Core I have the files YML that expose previously. I don't want
dependencyInjector and eventsManager properties.


Example mi PhalconController.yml:

Phalcon\DI\Injectable:
    exclusion_policy: NONE




[propertyMetadata] => Array
        (
            [_dependencyInjector] =>
JMS\Serializer\Metadata\PropertyMetadata Object
                (
                    [class] => Phalcon\Di\Injectable
                    [name] => _dependencyInjector
                    [reflection] => ReflectionProperty Object
                        (
                            [name] => _dependencyInjector
                            [class] => Phalcon\Di\Injectable
                        )

                )

            [_eventsManager] => JMS\Serializer\Metadata\PropertyMetadata
Object
                (
                    [class] => Phalcon\Di\Injectable
                    [name] => _eventsManager
                    [reflection] => ReflectionProperty Object
                        (
                            [name] => _eventsManager
                            [class] => Phalcon\Di\Injectable
                        )

                )

            [hotel] => JMS\Serializer\Metadata\PropertyMetadata Object
                (
                    [sinceVersion] =>
                    [untilVersion] =>
                    [groups] =>
                    [serializedName] => Hotel
                    [type] => Array
                        (
                            [name] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\HotelAType
                            [params] => Array
                                (
                                )

                        )

                    [class] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType
                    [name] => hotel
                    [reflection] => ReflectionProperty Object
                        (
                            [name] => hotel
                            [class] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType
                        )

                )

            [mealPlans] => JMS\Serializer\Metadata\PropertyMetadata Object
                (
                    [sinceVersion] =>
                    [untilVersion] =>
                    [groups] =>
                    [serializedName] => MealPlans
                    [type] => Array
                        (
                            [name] => array
                            [params] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType\MealPlansAType\MealPlanAType
                                            [params] => Array
                                                (
                                                )

                                        )

                                )

                        )
                    [class] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType
                    [name] => mealPlans
                    [reflection] => ReflectionProperty Object
                        (
                            [name] => mealPlans
                            [class] =>
Igm\Synergy\Controllers\Boards\HotelMealPlansNotifRSType
                        )

                )

        )

2017-06-02 12:33 GMT+02:00 Asmir Mustafic <notifications@github.com>:

**Comment by goetas** [comment]
are the phalcon metadta files in right places?


```php
$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Phalcon', 'Phalcon');
```

```yml
# named DI.Injectable.yml
Phalcon\DI\Injectable:
    exclusion_policy: NONE
```
```yml
# named Controller.yml
PhalconController:
    exclusion_policy: NONE
```

You have to make sure that metadata files have the right names... you can debug it editing a bit: https://github.com/schmittjoh/metadata/blob/master/src/Metadata/Driver/FileLocator.php#L34

**Comment by victorgp89** [comment]
[image: Imágenes integradas 1]


//add Soap BaseController info
$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Core',
'Igm\Synergy\Application\Core');
$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Phalcon',
'Phalcon\DI\Injectable');
$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Phalcon',
'Phalcon\Mvc\Controller');


The problem may be that the classes I want to serialize are from the
phalcon framework?
The namespace is from framework. I don't understand the error.


2017-06-02 12:45 GMT+02:00 Asmir Mustafic <notifications@github.com>:

**Comment by goetas** [comment]
it has to be:

```php

$serializeBuilder->addMetadataDir(APPROOT . '/metadata/Phalcon',
'Phalcon');
```

and place all metadata fines in `APPROOT . '/metadata/Phalcon`

(only once)
