### ISSUE TITLE
Location to save JMS metadata

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client#12]
Hi, 
I have this config.yml: 
```yml
soap_client: ~
xsd2php:
  namespaces:
    'http://dev.synergy.app/login': 'Igm\Synergy\Login'
    'http://dev.synergy.app/schema': 'Igm\Synergy\Schema'
    'http://dev.synergy.app/exception': 'Igm\Synergy\Exception'
    'http://dev.synergy.app/mealplans': 'Igm\Synergy\Controllers\Mealplans'
  destinations_php:
   'Igm\Synergy\Controllers\Mealplans': src/application/controllers/mealplans
   'Igm\Synergy\Schema': src/application/schema
   'Igm\Synergy\Login': src/application/login
   'Igm\Synergy\Exception': src/application/exception
  destinations_jms:
    'Igm\Synergy\Controllers\MealPlans': metadata/mealplans
    'Igm\Synergy\Login': metadata/login
    'Igm\Synergy\Exception': metadata/exception
wsdl2php:
  metadata:
    '/var/www/igm_xml/include/mealplan.wsdl': ~
```

The classes generate correctly but I have this error: 

Unable to determine location to save JMS metadata for class 'Igm\Synergy\Controllers\Mealplans\SoapEnvelope\Headers\GetMealPlansInput

**Comment by goetas** [comment]
you have created https://github.com/goetas-webservices/soap-server/issues/1 time ago, have you tried the solutions exposed there?

**Comment by victorgp89** [comment]
Yes, the problem is when I execute: 

vendor/igm/soap/bin/soap-client.php -vvv generate app/config.yml src/Service/Container

**Comment by goetas** [comment]
`Igm\Synergy\Controllers\MealPlans` vs `Igm\Synergy\Controllers\Mealplans`

case sensitivity
