### ISSUE TITLE
Operation name in SoapStub class

### ISSUE THREAD

**Issue by riccardonar** [goetas-webservices/soap-client#26]
I have this operation name OTA_HotelRateAmountNotif, it is transformed in oTAHotelRateAmountNotif in SoapStub class.
https://github.com/goetas-webservices/soap-client/blob/049195ef277abce548d05348cfd51dd96d0f7cc6/src/StubGeneration/ClientStubGenerator.php#L109

The operation oTAHotelRateAmountNotif isn't find by your Client because it checks the key of operations array only by strtolower in `findOperation`
https://github.com/goetas-webservices/soap-client/blob/049195ef277abce548d05348cfd51dd96d0f7cc6/src/Client.php#L141

A solution can be to compile operations array key with same strategy
https://github.com/goetas-webservices/soap-client/blob/049195ef277abce548d05348cfd51dd96d0f7cc6/src/Metadata/Generator/MetadataGenerator.php#L91

Or is it better to remove the camelize transformation in Stub generator?

**Comment by goetas** [comment]
Im fine with  having the  array key with same strategy

**Comment by goetas** [comment]
fixed by https://github.com/goetas-webservices/soap-client/pull/28
