### ISSUE TITLE
Soap Security Header

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client#37]
![image](https://user-images.githubusercontent.com/9083812/52937353-37a54b00-335f-11e9-8522-b7ef6939461a.png)

These namespaces must be indicated in the config.yml? Thanks a lot.

**Comment by goetas** [comment]
generally yes. I suggest you to have a look at https://github.com/goetas-webservices/soap-client/pull/9

**Comment by victorgp89** [comment]
Because I've this wsdl : https://cmtpi.siteminder.com/siteconnect/services/siteconnect_v1.1.0.wsdl

And process to generate PHP classes and metadatas give me this error: 

![image](https://user-images.githubusercontent.com/9083812/52938240-7a682280-3361-11e9-8475-07f3e1566a62.png)


My yml is like this: 

![image](https://user-images.githubusercontent.com/9083812/52938262-87851180-3361-11e9-8c0c-bfad36534b46.png)

**Comment by victorgp89** [comment]
In this case I can't solve where the problem is.

**Comment by victorgp89** [comment]
Or should I take all the commit changes that you mentioned above?

**Comment by goetas** [comment]
as you can see https://github.com/goetas-webservices/soap-client/pull/9 is not complete, you can try to continue on it https://github.com/goetas-webservices/soap-client/pull/9

**Comment by victorgp89** [comment]
But adding the namespace in the yml could not deserialize the headers?

**Comment by goetas** [comment]
not really. WSI headers are too complex

**Comment by victorgp89** [comment]
Sorry for the inconvenience, because I don't know very well what generates the problem.

If I create the metadatas, headerHandlers and PHP classes from the SoapSecuritym. What do you think would be the next step when processing the header of the wsdl that you have given me?

The library xsd2php accept the attributes: 
  any_element: true
  any_attribute: true

I think this is in YamlDriver but I can see. 

Sorry for this. Is for try to solve the problem because for my project I need to be able to process those headers.

Thanks for advance,
Victor

**Comment by victorgp89** [comment]
I try this yml:

**Comment by victorgp89** [comment]
![image](https://user-images.githubusercontent.com/9083812/52949151-bf00b780-337b-11e9-808d-7eda2d3e3384.png)

I try this yml after create the security xsd but the problem persist: 

![image](https://user-images.githubusercontent.com/9083812/52949180-d344b480-337b-11e9-99e3-f158c097f02e.png)

**Comment by victorgp89** [comment]
Any update about this? Sorry for disturb

**Comment by victorgp89** [comment]
And another simple question: 

The attributes in yml: any_element and any_attribute are available in xsd2php project? 

Because I have the following error: 

Call to undefined method WssWsSecurity\Secext\Security::addToAnyElement()

**Comment by goetas** [comment]
I suggest you to have a look at as #9 
there you have see how to deal with any-type

**Comment by victorgp89** [comment]
It's possible to skips this headers in the process to convert wsdl in php classes and SoapContainer?

Because always return the same: 

Can't find the Attribute named {http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd}#Id.

**Comment by victorgp89** [comment]
Because I need to generate the metadata and PHP classes from this wsdl: 

https://cmtpi.siteminder.com/siteconnect/services/siteconnect_v1.1.0.wsdl

**Comment by victorgp89** [comment]
The last thing, it would be possible to generate a subscriber to extract the header, process it manually and let go with the process.

![image](https://user-images.githubusercontent.com/9083812/53252072-69e7dd00-36be-11e9-8e6d-9e7d05f0b933.png)

But this is not generic.

Thanks for advance.
