### ISSUE TITLE
Multiple xml_root_namespace

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client#43]
Hi, 
Is it possible to configure several attributes of this type?

For example: 

![image](https://user-images.githubusercontent.com/9083812/63849937-5b42f100-c993-11e9-8164-3bc845bccc0b.png)

In my api we have clients that also send this version of OTA but without the xmls attribute

![image](https://user-images.githubusercontent.com/9083812/63850098-a3621380-c993-11e9-8e68-6457514d9aad.png)

**Comment by goetas** [comment]
The xml you posted is not a valid OTA request.
By OTA specifications elements are namespaced. If you have such case, I suggest you to add the xmlns before processing the document.
