### ISSUE TITLE
Is there a way to see/print the request and response messages?

### ISSUE THREAD

**Issue by etcware** [goetas-webservices/soap-client#57]
Is there a way to see/print the request and response messages? Something like a debug or test feature to print a log file with these messages? I would like to tag this as "help wanted" but I don't know how ...

**Comment by goetas** [comment]
The `ClientFactory` has a method `setHttpClient`, that method accepts any `Http\Client\HttpClient` instance. 
You can provide there a custom guzzle implementation that logs the requests/responses where you prefer (as example https://github.com/gmponos/guzzle-log-middleware)
