### ISSUE TITLE
Missing symfony/yaml dependency

### ISSUE THREAD

**Issue by tuupola** [goetas-webservices/soap-client#8]
After installing dependencies with `composer install --no-dev` the `symfony/yaml` library is missing. Can be fixed by installing the library manually. This behaviour is not seen this in development since `symfony/yaml` is required by `goetas-webservices/wsdl2php`.

**Comment by goetas** [comment]
solved with https://github.com/goetas-webservices/xsd2php-runtime/commit/94a406c8ff8f353d0f97e3ee5613b5c9dfa1a878
